# Generated by Django 3.1.1 on 2020-09-29 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField()),
                ('content', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
