# Generated by Django 3.1.1 on 2020-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
