# Generated by Django 3.1.1 on 2020-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_posts_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
